### ISSUE TITLE
Remove Actual Credentials 

### ISSUE THREAD

**Issue by douglascayers** [junliu724515/WizardBaseComponent#1]
Your actual user/pass credentials are committed to `/scripts/source_env.sh` and `/scripts/target_env.sh`

If this was not your intention, I recommend you change your password and remove the user/pass from any publically committed repos.

Had Salesforce not forced login verification from new location I would have been able to access this developer org.

![image](https://cloud.githubusercontent.com/assets/4142577/21083352/273b07ee-bfb4-11e6-9168-e365aa451f60.png)

**Comment by junliu724515** [comment]
Thanks a lot Doug, I modified the files
